//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactSqlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTable
    {
        public int PinCode { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> Number { get; set; }
        public System.DateTime DateCreation { get; set; }
    }
}
